# Generated by Django 3.2.5 on 2022-06-05 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220530_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Product  name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_product', to='main.category')),
            ],
            options={
                'verbose_name': 'Shoe',
                'verbose_name_plural': 'Shoes',
            },
        ),
        migrations.AlterField(
            model_name='brand',
            name='shoes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_brand_name', to='main.product'),
        ),
        migrations.DeleteModel(
            name='Shoes',
        ),
    ]
