# Generated by Django 3.2.5 on 2022-06-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220605_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Brand price'),
        ),
    ]
